export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};
import Image from "next/image";
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <body className="w-full">
      <header className=" h-96 w-96 bg-red-500 font-bold">
        Hey, what's going on here
      </header>
      {children}
    </body>
  );
}
