import { type NextPage } from "next";
import Head from "next/head";
import Headline from "~/layouts/Headline";
import AdminMutations from "~/components/AdminMutations";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>

        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Headline>Admin</Headline>
      <main>
        <AdminMutations />
      </main>
    </>
  );
};

export default Home;
